# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'App' do
  use_frameworks!

  pod 'R.swift', '5.0.2'
  pod 'SwiftLint', '0.30.1'
  pod 'SwiftyBeaver', '1.6.1'
  pod 'XRouter', '1.2.1'

  target 'AppTests' do
    inherit! :search_paths

    # Insert test only pods here...

  end

end
